name: weathercompanion
description: A friendly AI-powered weather forecast companion app.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.1
  latlong2: ^0.9.0
  geolocator: ^11.1.0
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1   # ✅ stays here

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
