# lib/pubspec.yaml

name: weathercompanion
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.20.2
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_gemini: ^3.0.0
  shared_preferences: ^2.2.3
  latlong2: ^0.9.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png