# lib/pubspec.yaml

name: weathercompanion
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.19.0
  flutter_map: ^6.1.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  flutter_gemini: ^3.0.0
  shared_preferences: ^2.2.3
  # nominatim_geocoding: ^0.0.6  <-- DELETE THIS LINE
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png